package com.example.libraryApp;

public enum BorrowingStatus {
    BORROWED, IN_LIBRARY, RETURNED, RETURNED_SUCCESSFULLY, BORROWED_SUCCESSFULLY, BORROWED_BY_CURRENT_USER, ADDED_TO_QUEUE, PASSED_TO_NEXT_USER
}
